# This file configures the latexmk command you can use to compile
# the pdf version of the blueprint
$pdf_mode = 1;
# -interaction=nonstopmode: never block on a LaTeX error waiting for terminal input
$pdflatex = 'xelatex -synctex=1 -interaction=nonstopmode';
@default_files = ('print.tex');
